version: '3'

services:
  bdlocal:
    container_name: app-bd-local
    image: arm64v8/mysql:8
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
      interval: 20s
      timeout: 10s
      retries: 120
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user123"
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    networks:
      - app-network-local

  apilocal:
    container_name: app-api-local
    image: williammian/app-api:arm64v8
    environment:
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "user123"
      DATABASE_URL: "jdbc:mysql://app-bd-local:3306/app?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true"
      SERVER_PORT: "8080"
    ports:
      - 8080:8080
    depends_on:
      bdlocal:
        condition: service_healthy
    networks:
      - app-network-local

  weblocal:
    container_name: app-web-local
    image: williammian/app-web:arm64v8
    environment:
      API_URL: "http://169.76.95.30:8080/api" #IP da server api
    ports:
      - 80:80
    depends_on:
      - apilocal
    networks:
      - app-network-local

networks:
  app-network-local:
    driver: bridge
