version: '3.0'
services:

  bd:
    container_name: app-bd
    image: mysql:8
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
      interval: 20s
      timeout: 10s
      retries: 120
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user123"
      MYSQL_DATABASE: "app"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    networks:
      - app-network
  
  api:
    container_name: app-api
    image: williammian/appapi
    deploy:
      resources:
        limits:
          memory: 800M
    environment:
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "user123"
      DATABASE_URL: "jdbc:mysql://app-bd:3306/app?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true"
    ports:
      - 8080:8080
    depends_on:
      bd:
        condition: service_healthy
    networks:
      - app-network
      
  web:
    container_name: app-web
    image: williammian/appweb
    environment:
      API_URL: "http://localhost:8080"
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network: 
    driver: bridge