version: '3.0'
services:
  
  api:
    container_name: app-api
    image: williammian/appapi
    deploy:
      resources:
        limits:
          memory: 800M
    environment:
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "user123"
      DATABASE_URL: "jdbc:mysql://app-bd:3306/app?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true"
      SERVER_PORT: "8080"
    ports:
      - 8080:8080
    networks:
      - bd_default
      
networks:
  bd_default:
    external: true

